### PR TITLE
Hotfix cleaning lady

### PR DESCRIPTION
**Pull request by User12837985123**
I have now cleaned the house.

### CODE REVIEW

**Review by Sworgon — APPROVED** [review]
Looks cool

**Review by KVISDAOWNER — CHANGES_REQUESTED** [review]
Looks good. I would like to also have removed the DeadReckoningService todo "//TODO: Remove me at some point" and the associated log

**Review by Sworgon — DISMISSED** [review]
Still looks good

**Review by Sworgon — DISMISSED** [review]
Looks alright

**Review by KVISDAOWNER — APPROVED** [review]

**Review by Sworgon — APPROVED** [review]
It looks alright still

**Pull request merged**
